# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppointmentForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from homepage import Ui_MainWindow
from shopping import Ui_ShoppingWindow

class Ui_AppointmentWindow(object):

    def openWindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_ShoppingWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(850, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 500, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(100, 100, 360, 300))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.calendarWidget.setFont(font)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 400, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 405, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.openWindow())
        self.pushButton.setGeometry(QtCore.QRect(120, 450, 350, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, -60, 1961, 741))
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label.raise_()
        self.calendarWidget.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1930, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Set Appointment"))
        self.label_2.setText(_translate("MainWindow", "Select Date:"))
        self.label_3.setText(_translate("MainWindow", "Select Time:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "(Add Time)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "09:00"))
        self.comboBox.setItemText(2, _translate("MainWindow", "10:00"))
        self.comboBox.setItemText(3, _translate("MainWindow", "11:00"))
        self.comboBox.setItemText(4, _translate("MainWindow", "12:00"))
        self.comboBox.setItemText(5, _translate("MainWindow", "13:00"))
        self.comboBox.setItemText(6, _translate("MainWindow", "14:00"))
        self.comboBox.setItemText(7, _translate("MainWindow", "15:00"))
        self.comboBox.setItemText(8, _translate("MainWindow", "16:00"))
        self.comboBox.setItemText(9, _translate("MainWindow", "17:00"))
        self.pushButton.setText(_translate("MainWindow", "Choose Appointment"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/backgroundimage (2).png\"/></p></body></html>"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AppointmentWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
